export function check_cards(): void;
export function hide_all_effects(): void;
export function show_all_effects(): void;
export function reset_filters(): void;
export function check_selected_cards(): boolean;
export function deselect_all_cards(): void;
export function select_visible_cards(): void;
export function generate_yaml(): void;
export function copy_yaml_to_clipboard(): void;
